In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [2]:
from google.colab import files

uploaded = files.upload()



Saving company.csv to company.csv


In [3]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "company.csv" with length 4060 bytes


In [34]:
market=pd.read_csv( "company.csv" )
df=market.copy()
df=df.dropna()
df.head


<bound method NDFrame.head of         TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]>

In [35]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [37]:
df.duplicated().sum()

0

In [38]:
X=df[['TV', 'Radio', 'Newspaper']]
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [39]:
y=df['Sales']
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=22)

In [41]:
X_train.shape

(160, 3)

In [42]:
X_test.shape

(40, 3)

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

Lİnear regression

In [44]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)
y_predict=model.predict(X_test)
y_predict

array([11.50507377, 12.84657448, 10.04888489, 25.09113852, 17.37413795,
        8.05165564,  6.34463349,  8.52288741, 20.86952766, 10.67375447,
        6.90960915, 21.3370343 , 21.14114468, 19.63689246, 15.26478613,
       10.59635524, 21.76659335, 23.73688945, 12.24645122,  9.96345917,
       16.48537769, 20.26806554, 20.25869843, 15.95683049, 15.8195745 ,
       18.01683959, 12.26397709,  9.64733425, 17.92498036, 23.68316413,
       13.2979892 , 17.52679223,  8.84379613, 13.26050311,  9.7435341 ,
       10.59426893, 16.60937563, 18.29939873, 11.2821882 ,  9.37792978])

In [45]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_predict)

0.10295763234650994

In [46]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.91164209732733

In [47]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_predict)

2.4260517694737644

RandomForestRegressor 

In [48]:
from sklearn.ensemble import RandomForestRegressor 
model=RandomForestRegressor (n_estimators=100,random_state=22)
model.fit(X_train,y_train)
y_predi=model.predict(X_test)
y_predi

array([11.764, 13.181, 11.483, 25.099, 20.23 ,  3.929,  7.5  ,  9.211,
       19.435,  9.317,  6.744, 19.145, 19.206, 18.731, 15.083, 11.076,
       23.228, 25.668, 11.133,  8.748, 15.804, 19.369, 18.953, 17.571,
       16.517, 18.083, 11.863,  7.857, 17.125, 19.932, 13.632, 17.338,
        8.541, 16.482, 11.436, 11.745, 15.286, 20.817, 10.119,  6.353])

In [52]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_predi)

0.0787732478768419

In [50]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predi)

0.9282146803559008

In [51]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_predi)

1.9710166999999952

SupportVector

In [58]:
market=pd.read_csv( "company.csv" )

In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [60]:
X = market.iloc[:, [1,2]].values
y = market.iloc[:, 3].values


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 22)

In [62]:
from sklearn.svm import SVR
classifier = SVR(kernel='linear')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
y_pred 

array([15.0113396 , 12.30118331, 12.42369679, 20.27007544, 18.59741813,
       17.3543459 , 12.46875558, 14.11300937, 18.77043715, 21.10213651,
       14.28036181, 17.57341218, 18.10460472, 17.60928859, 20.13664547,
       14.05918327, 20.78534442, 19.85293341, 20.49593048, 19.16239942,
       18.35498001, 18.76354996, 18.39128379, 15.49705828, 12.78800118,
       13.41379258, 13.21815965, 18.95830353, 18.44020125, 17.56679404,
       19.04223034, 20.1952096 , 16.26830762, 12.30073133, 13.77915925,
       13.20675428, 20.07976623, 19.58758774, 18.10119804, 19.18360979,
       20.39644759, 13.97767468, 15.48655686, 14.81674435, 19.31078747,
       15.73216953, 17.16812751, 14.98342497, 12.63500883, 13.64273766])

In [63]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

0.40910398729049824

In [64]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-0.0794521078405328

In [65]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

28.8818896823162

In [67]:
data = [['Linear',0.0787732478768419,0.9282146803559008,1.9710166999999952
 ], ['Random Forrest',0.10295763234650994, 0.91164209732733,2.4260517694737644], ['SupportVector',0.40910398729049824,0.0794521078405328,28.8818896823162]]
summary = pd.DataFrame(data, columns=['Model',  'MAPE','R2','MSE'])
summary

Model      MAPE        R2        MSE
0          Linear  0.078773  0.928215   1.971017
1  Random Forrest  0.102958  0.911642   2.426052
2   SupportVector  0.409104  0.079452  28.881890